---
- name: Install Apache WebServer
  hosts: all
  become: true

  tasks:
    - name: Install Apache on Ubuntu Server
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Ubuntu"

    - name: Install Apache on Red Hat  Server
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
