---
- name: Install packages thru loop
  hosts: 172.31.13.32
  become: true
  vars:
    packages: [telnet,htop]  

  tasks:
    - name: Install packages
      yum:
        name: ‘{{ packages }}’
        state: present
