---
- name: Fine a process and kill it
  hosts: 172.31.13.32 

  tasks:
    - name: get running processes from remote hosts
      ignore_errors: yes
      shell: "ps -few | grep top | awk '{print$2}'"
      register: running_process
   
    - name: Kill running processes
      ignore_errors: yes
      shell: "kill {{ item }}"
      with_items: " {{ running_process.stdout_lines }}"
