---
- name: Installing and running apache
  hosts: 172.31.13.32
  become: true

  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: present

  - name: start httpd
    service:
      name: httpd
      state: started
